// AUTO-GENERATED by tools/pyq_exporter/extract_pyq.py — DO NOT EDIT BY HAND.
//
// Regenerated from 1 paper(s) in pyq-inbox/out/*.json on every exporter run.
// To change anything here, fix the source JSON (or the PDF) and re-run:
//     pyq-inbox/import-pyq.bat   |   npm run pyq:rebuild
//
// Wired into src/data/mockData.ts: imported papers surface to students as mock
// tests (questions grouped under sub-heads) and in the PYQ archive.

import { PYQPaper, MockTest } from '../../types';

export const GENERATED_PYQ_PAPERS = [
  {
    "id": "pyq-ssc-cgl-2023-paper-i",
    "examId": "ssc-cgl",
    "examName": "SSC CGL",
    "year": 2023,
    "paperType": "Paper I",
    "totalQuestions": 2,
    "downloadAvailable": true,
    "frequencyTags": [
      "General"
    ],
    "questions": [
      {
        "id": "pyq-ssc-cgl-2023-paper-i-q001",
        "questionNumber": 1,
        "examId": "ssc-cgl",
        "subject": "General Studies",
        "topic": "Modern Indian History",
        "stem": "Who was the first Prime Minister of India?",
        "options": [
          {
            "id": "A",
            "text": "Jawaharlal Nehru"
          },
          {
            "id": "B",
            "text": "Sardar Patel"
          },
          {
            "id": "C",
            "text": "Mahatma Gandhi"
          },
          {
            "id": "D",
            "text": "Rajendra Prasad"
          }
        ],
        "correctOption": "A",
        "explanation": "Jawaharlal Nehru served as the first Prime Minister of India from 1947 to 1964.",
        "difficulty": "EASY",
        "questionType": "CONCEPTUAL",
        "sourceType": "PYQ",
        "pyqYear": 2023,
        "pyqExam": "SSC CGL"
      },
      {
        "id": "pyq-ssc-cgl-2023-paper-i-q002",
        "questionNumber": 2,
        "examId": "ssc-cgl",
        "subject": "General Science",
        "topic": "Chemistry",
        "stem": "What is the pH value of pure water at 25 degrees Celsius?",
        "options": [
          {
            "id": "A",
            "text": "5"
          },
          {
            "id": "B",
            "text": "6"
          },
          {
            "id": "C",
            "text": "7"
          },
          {
            "id": "D",
            "text": "9"
          }
        ],
        "correctOption": "C",
        "explanation": "Pure water has a pH of 7 at 25 C, which is neutral on the pH scale.",
        "difficulty": "EASY",
        "questionType": "CONCEPTUAL",
        "sourceType": "PYQ",
        "pyqYear": 2023,
        "pyqExam": "SSC CGL"
      }
    ]
  }
] as unknown as PYQPaper[];

export const GENERATED_PYQ_MOCK_TESTS = [
  {
    "id": "mock-pyq-ssc-cgl-2023-paper-i",
    "title": "SSC CGL (2023) — Paper I",
    "examId": "ssc-cgl",
    "paperName": "Paper I",
    "durationMinutes": 30,
    "totalMarks": 2,
    "negativeMarksPerIncorrect": 0.25,
    "sections": [
      {
        "id": "sec-general",
        "name": "General",
        "totalQuestions": 2,
        "questions": [
          {
            "id": "pyq-ssc-cgl-2023-paper-i-q001",
            "questionNumber": 1,
            "examId": "ssc-cgl",
            "subject": "General Studies",
            "topic": "Modern Indian History",
            "stem": "Who was the first Prime Minister of India?",
            "options": [
              {
                "id": "A",
                "text": "Jawaharlal Nehru"
              },
              {
                "id": "B",
                "text": "Sardar Patel"
              },
              {
                "id": "C",
                "text": "Mahatma Gandhi"
              },
              {
                "id": "D",
                "text": "Rajendra Prasad"
              }
            ],
            "correctOption": "A",
            "explanation": "Jawaharlal Nehru served as the first Prime Minister of India from 1947 to 1964.",
            "difficulty": "EASY",
            "questionType": "CONCEPTUAL",
            "sourceType": "PYQ",
            "pyqYear": 2023,
            "pyqExam": "SSC CGL"
          },
          {
            "id": "pyq-ssc-cgl-2023-paper-i-q002",
            "questionNumber": 2,
            "examId": "ssc-cgl",
            "subject": "General Science",
            "topic": "Chemistry",
            "stem": "What is the pH value of pure water at 25 degrees Celsius?",
            "options": [
              {
                "id": "A",
                "text": "5"
              },
              {
                "id": "B",
                "text": "6"
              },
              {
                "id": "C",
                "text": "7"
              },
              {
                "id": "D",
                "text": "9"
              }
            ],
            "correctOption": "C",
            "explanation": "Pure water has a pH of 7 at 25 C, which is neutral on the pH scale.",
            "difficulty": "EASY",
            "questionType": "CONCEPTUAL",
            "sourceType": "PYQ",
            "pyqYear": 2023,
            "pyqExam": "SSC CGL"
          }
        ]
      }
    ]
  }
] as unknown as MockTest[];
