// AUTO-GENERATED by tools/pyq_exporter/extract_pyq.py — DO NOT EDIT BY HAND.
//
// Regenerated from 0 paper(s) in pyq-inbox/out/*.json on every exporter run.
// To change anything here, fix the source JSON (or the PDF) and re-run:
//     pyq-inbox/import-pyq.bat   |   npm run pyq:rebuild
//
// Wired into src/data/mockData.ts: imported papers surface to students as mock
// tests (questions grouped under sub-heads) and in the PYQ archive.

import { PYQPaper, MockTest } from '../../types';

export const GENERATED_PYQ_PAPERS = [] as unknown as PYQPaper[];

export const GENERATED_PYQ_MOCK_TESTS = [] as unknown as MockTest[];
