# -*- coding: utf-8 -*-
import json
import os

civil_questions = [
    # --- RCC & PRESTRESSED (1 - 15) ---
    {
        "qNum": 1,
        "subject": "Reinforced Concrete Structures",
        "topic": "Limit State Design — Flexure",
        "subtopic": "Limiting Neutral Axis Depth",
        "stem": "As per IS 456:2000, what is the limiting depth of neutral axis (xu,max / d) for Fe 500 grade steel in limit state design of flexural members?",
        "options": ["0.53", "0.48", "0.46", "0.44"],
        "correct": "C",
        "formula": "xu,max / d = 0.0035 / (0.0055 + 0.87 * fy / Es)",
        "explanation": "According to IS 456:2000 Clause 38.1 Note, linear strain compatibility gives xu,max/d = 0.53 for Fe 250, 0.48 for Fe 415, 0.46 for Fe 500, and 0.44 for Fe 550.",
        "ref": "IS 456:2000, Clause 38.1",
        "diff": "EASY",
        "year": 2024
    },
    {
        "qNum": 2,
        "subject": "Reinforced Concrete Structures",
        "topic": "Shear and Bond",
        "subtopic": "Development Length",
        "stem": "The development length (Ld) of a tension reinforcing bar of nominal diameter φ is given by IS 456:2000 as:",
        "options": ["Ld = (φ · σs) / (2 · τbd)", "Ld = (φ · σs) / (4 · τbd)", "Ld = (φ · σs) / (8 · τbd)", "Ld = (2 · φ · σs) / (3 · τbd)"],
        "correct": "B",
        "formula": "Ld = (φ · σs) / (4 · τbd)",
        "explanation": "Per IS 456:2000 Cl. 26.2.1, equating tensile bar force to bond resistance yields Ld = (φ · σs) / (4 · τbd). For deformed bars (HYSD), τbd is increased by 60%. For bars in compression, τbd is increased by 25%.",
        "ref": "IS 456:2000 Cl. 26.2.1",
        "diff": "EASY",
        "year": 2023
    },
    {
        "qNum": 3,
        "subject": "Reinforced Concrete Structures",
        "topic": "Beams & Slabs",
        "subtopic": "Minimum Tensile Reinforcement",
        "stem": "As per IS 456:2000, the minimum area of tension reinforcement in a rectangular beam shall not be less than:",
        "options": ["As / (b · d) = 0.85 / fy", "As / (b · d) = 0.40 / fy", "As / (b · D) = 0.12%", "As / (b · d) = 0.04 · b · d"],
        "correct": "A",
        "formula": "As,min / (b · d) = 0.85 / fy",
        "explanation": "IS 456:2000 Clause 26.5.1.1 specifies that the minimum area of tension reinforcement in beams is As,min = (0.85 · b · d) / fy, where b is width of beam, d is effective depth, and fy is characteristic steel strength.",
        "ref": "IS 456:2000 Cl. 26.5.1.1",
        "diff": "EASY",
        "year": 2022
    },
    {
        "qNum": 4,
        "subject": "Reinforced Concrete Structures",
        "topic": "Shear Design",
        "subtopic": "Critical Section for Shear",
        "stem": "In a simply supported RCC beam resting on masonry support subjected to uniformly distributed load, the critical section for checking nominal shear stress (τv) is located at a distance of:",
        "options": ["d/2 from the face of support", "d from the face of support", "At the center of support", "2d from the face of support"],
        "correct": "B",
        "formula": "Critical section distance = effective depth (d) from support face",
        "explanation": "According to IS 456:2000 Clause 31.6.2 and 22.6.2, when the reaction introduces compression into the end regions of the member, the critical section for shear is taken at a distance d (effective depth) from the face of the support.",
        "ref": "IS 456:2000 Cl. 22.6.2 & 31.6.2",
        "diff": "MEDIUM",
        "year": 2024
    },
    {
        "qNum": 5,
        "subject": "Reinforced Concrete Structures",
        "topic": "Shear Reinforcement",
        "subtopic": "Maximum Stirrup Spacing",
        "stem": "As per IS 456:2000, the maximum spacing of vertical shear stirrups along the axis of the beam shall not exceed:",
        "options": ["0.75 d or 300 mm, whichever is less", "d or 300 mm, whichever is less", "0.75 d or 450 mm, whichever is less", "0.50 d or 300 mm, whichever is less"],
        "correct": "A",
        "formula": "Spacing Sv ≤ min(0.75 d, 300 mm)",
        "explanation": "Clause 26.5.1.5 of IS 456:2000 states that the spacing of stirrups measured along the member axis shall not exceed 0.75 d for vertical stirrups and d for inclined stirrups at 45°, but in no case shall it exceed 300 mm.",
        "ref": "IS 456:2000 Cl. 26.5.1.5",
        "diff": "EASY",
        "year": 2023
    },
    {
        "qNum": 6,
        "subject": "Reinforced Concrete Structures",
        "topic": "Slab Design",
        "subtopic": "Maximum Bar Diameter in Slabs",
        "stem": "The diameter of reinforcing bars in a slab shall not exceed what fraction of the total thickness of the slab as per IS 456:2000?",
        "options": ["One-fourth (1/4) of total thickness", "One-eighth (1/8) of total thickness", "One-tenth (1/10) of total thickness", "One-sixth (1/6) of total thickness"],
        "correct": "B",
        "formula": "φ_bar ≤ D_slab / 8",
        "explanation": "According to IS 456:2000 Clause 26.5.2.2, the diameter of reinforcing bars shall not exceed one-eighth of the total thickness of the slab.",
        "ref": "IS 456:2000 Cl. 26.5.2.2",
        "diff": "EASY",
        "year": 2021
    },
    {
        "qNum": 7,
        "subject": "Reinforced Concrete Structures",
        "topic": "Durability & Concrete Mix",
        "subtopic": "Minimum Grade for Severe Exposure",
        "stem": "As per IS 456:2000 Table 5, what is the minimum grade of concrete recommended for reinforced concrete (RCC) exposed to 'Severe' environmental conditions?",
        "options": ["M 20", "M 25", "M 30", "M 35"],
        "correct": "C",
        "formula": "Severe exposure min grade = M 30",
        "explanation": "Per IS 456 Table 5, minimum grades for RCC under environmental exposure conditions are: Mild (M20), Moderate (M25), Severe (M30), Very Severe (M35), and Extreme (M40).",
        "ref": "IS 456:2000 Table 5",
        "diff": "MEDIUM",
        "year": 2024
    },
    {
        "qNum": 8,
        "subject": "Reinforced Concrete Structures",
        "topic": "Limit State Philosophy",
        "subtopic": "Partial Safety Factors",
        "stem": "In the limit state of collapse, the partial safety factors for concrete (γc) and steel (γs) are taken as:",
        "options": ["1.15 and 1.50 respectively", "1.50 and 1.15 respectively", "1.50 and 1.00 respectively", "1.20 and 1.15 respectively"],
        "correct": "B",
        "formula": "γc = 1.50, γs = 1.15 (Collapse)",
        "explanation": "Concrete has higher variability in material preparation and compaction on site compared to factory-controlled steel. Hence IS 456 adopts γc = 1.50 and γs = 1.15 in Limit State of Collapse (Clause 36.4.2).",
        "ref": "IS 456:2000 Cl. 36.4.2",
        "diff": "EASY",
        "year": 2022
    },
    {
        "qNum": 9,
        "subject": "Reinforced Concrete Structures",
        "topic": "Flexural Failure Modes",
        "subtopic": "Under-reinforced Beam Characteristics",
        "stem": "An under-reinforced RCC beam section is preferred in structural design because:",
        "options": ["It undergoes sudden, brittle failure without prior warning", "Steel yields before concrete crushes, giving ample ductile deflection and crack warning", "It requires maximum amount of steel and minimizes beam depth", "Neutral axis depth exceeds the limiting neutral axis depth"],
        "correct": "B",
        "formula": "xu < xu,max; εs ≥ 0.87 fy / Es + 0.002 before concrete strain reaches 0.0035",
        "explanation": "Under-reinforced sections ensure that the tensile steel reaches its yield point long before concrete reaches its ultimate crushing strain (0.0035). This produces large visible cracks and deflections, ensuring ductile failure and safety.",
        "ref": "IS 456:2000 Cl. 38.1",
        "diff": "EASY",
        "year": 2024
    },
    {
        "qNum": 10,
        "subject": "Reinforced Concrete Structures",
        "topic": "Columns",
        "subtopic": "Minimum Eccentricity Check",
        "stem": "As per IS 456:2000, all columns shall be designed for minimum eccentricity emin given by:",
        "options": ["emin = L/500 + D/30, subject to a minimum of 20 mm", "emin = L/300 + D/20, subject to a minimum of 25 mm", "emin = L/500 + D/50, subject to a minimum of 15 mm", "emin = L/250 + D/30, subject to a minimum of 20 mm"],
        "correct": "A",
        "formula": "emin = max(L/500 + D/30, 20 mm)",
        "explanation": "IS 456:2000 Clause 25.4 specifies that all columns shall be designed for an unsupported length L and lateral dimension D with minimum eccentricity emin = unsupported length/500 + lateral dimension/30, subject to a minimum of 20 mm.",
        "ref": "IS 456:2000 Cl. 25.4",
        "diff": "MEDIUM",
        "year": 2023
    },
    {
        "qNum": 11,
        "subject": "Reinforced Concrete Structures",
        "topic": "Columns",
        "subtopic": "Short vs Slender Column Criteria",
        "stem": "A reinforced concrete column is classified as a 'Short Column' if the ratio of effective length (Leff) to its least lateral dimension (D or b) is:",
        "options": ["Greater than 12", "Less than 12", "Between 12 and 18", "Less than 3"],
        "correct": "B",
        "formula": "Slenderness ratio λ = Leff / b < 12 => Short Column",
        "explanation": "Clause 25.1.2 of IS 456 defines a short column as one where both effective length ratios (Lex / D and Ley / b) are less than 12. If either ratio is 12 or more, it is considered a slender (long) column.",
        "ref": "IS 456:2000 Cl. 25.1.2",
        "diff": "EASY",
        "year": 2021
    },
    {
        "qNum": 12,
        "subject": "Reinforced Concrete Structures",
        "topic": "Detailing of Reinforcement",
        "subtopic": "Nominal Cover for Footing",
        "stem": "As per IS 456:2000, what is the minimum nominal clear cover required for footing reinforcement cast directly against earth?",
        "options": ["25 mm", "40 mm", "50 mm", "75 mm"],
        "correct": "C",
        "formula": "Footing nominal cover = 50 mm",
        "explanation": "Clause 26.4.2.2 and Table 16 specify that the minimum nominal cover for footings is 50 mm. When concrete is placed directly against untreated soil without blinding layer, cover is commonly increased to 75 mm.",
        "ref": "IS 456:2000 Cl. 26.4.2.2",
        "diff": "EASY",
        "year": 2024
    },
    {
        "qNum": 13,
        "subject": "Reinforced Concrete Structures",
        "topic": "Bond & Anchorage",
        "subtopic": "Deformed Bars Bond Stress Increment",
        "stem": "For deformed bars conforming to IS 1786 (HYSD bars), the design bond stress values given in IS 456:2000 for plain bars in tension shall be increased by:",
        "options": ["25%", "40%", "50%", "60%"],
        "correct": "D",
        "formula": "τbd(deformed) = 1.60 · τbd(plain)",
        "explanation": "IS 456:2000 Clause 26.2.1.1 states: For deformed bars conforming to IS 1786, the design bond stress values for plain bars shall be increased by 60%.",
        "ref": "IS 456:2000 Cl. 26.2.1.1",
        "diff": "EASY",
        "year": 2023
    },
    {
        "qNum": 14,
        "subject": "Prestressed Concrete",
        "topic": "Prestressing Losses",
        "subtopic": "Losses in Pre-tensioned vs Post-tensioned",
        "stem": "Which of the following losses of prestress does NOT occur in pre-tensioned concrete members?",
        "options": ["Elastic shortening of concrete", "Shrinkage of concrete", "Friction between tendon and duct", "Creep of concrete"],
        "correct": "C",
        "formula": "Friction loss occurs only in curved post-tensioned ducts (IS 1343)",
        "explanation": "In pre-tensioning, tendons are stressed before concrete is poured and there are no ducts or curved profiles involving duct friction. Hence friction and wobble losses occur strictly in post-tensioned members.",
        "ref": "IS 1343:2012 Prestressed Concrete Code",
        "diff": "MEDIUM",
        "year": 2024
    },
    {
        "qNum": 15,
        "subject": "Reinforced Concrete Structures",
        "topic": "Torsion Design",
        "subtopic": "Equivalent Bending Moment",
        "stem": "As per IS 456:2000, under combined bending moment (M) and twisting moment (T), the equivalent bending moment (Me1) is expressed as:",
        "options": ["Me1 = M + T · (1 + D/b) / 1.7", "Me1 = M + T · (1 + b/D)", "Me1 = M + (T / 1.7)", "Me1 = √(M² + T²)"],
        "correct": "A",
        "formula": "Me1 = M + Mt = M + T · (1 + D/b) / 1.7",
        "explanation": "Clause 41.4.2 of IS 456 specifies that longitudinal reinforcement in members subjected to combined bending and torsion shall be designed for an equivalent bending moment Me1 = M + Mt, where Mt = T · (1 + D/b) / 1.7.",
        "ref": "IS 456:2000 Cl. 41.4.2",
        "diff": "HARD",
        "year": 2022
    },

    # --- STRUCTURAL ANALYSIS (16 - 27) ---
    {
        "qNum": 16,
        "subject": "Structural Analysis",
        "topic": "Determinate & Indeterminate Structures",
        "subtopic": "Static Indeterminacy of Trusses",
        "stem": "A 2D pin-jointed plane truss has m members, r external reaction components, and j joints. The degree of static indeterminacy (Ds) is given by:",
        "options": ["Ds = m - (2j - 3)", "Ds = m + r - 2j", "Ds = 2j - m - 3", "Ds = m + 3 - 2j"],
        "correct": "B",
        "formula": "Ds = (m + r) - 2j",
        "explanation": "For a 2D pin-jointed truss, total unknowns are m member forces plus r support reactions. Total equations of equilibrium are 2 per joint (2j). Hence static indeterminacy Ds = m + r - 2j.",
        "ref": "Structural Analysis by Hibbeler",
        "diff": "EASY",
        "year": 2024
    },
    {
        "qNum": 17,
        "subject": "Structural Analysis",
        "topic": "Kinematic Indeterminacy",
        "subtopic": "Degrees of Freedom in Fixed Beam",
        "stem": "What is the kinematic indeterminacy (degrees of freedom) of a fixed beam AB of span L, neglecting axial deformations?",
        "options": ["0", "1", "2", "3"],
        "correct": "A",
        "formula": "Dk = 0 for fixed beam with axial deformation neglected",
        "explanation": "Both ends A and B are fixed supports, where translations (Δx = 0, Δy = 0) and rotation (θ = 0) are completely restrained. Neglecting axial deformations, all joint displacements are zero, so Dk = 0.",
        "ref": "Theory of Structures by Ramamrutham",
        "diff": "EASY",
        "year": 2023
    },
    {
        "qNum": 18,
        "subject": "Structural Analysis",
        "topic": "Moment Distribution Method",
        "subtopic": "Carry-Over Factor",
        "stem": "In Moment Distribution Method, the carry-over factor to a far end that is fixed is:",
        "options": ["0", "0.50", "0.75", "1.00"],
        "correct": "B",
        "formula": "Carry Over Factor (COF) = +0.5 to a fixed far end",
        "explanation": "When a moment M is applied at the near end of a prismatic member with the far end fixed, a moment of M/2 with the same sign is induced at the fixed far end. Hence the carry-over factor is +1/2 or 0.50.",
        "ref": "Structural Analysis by C.K. Wang",
        "diff": "EASY",
        "year": 2022
    },
    {
        "qNum": 19,
        "subject": "Structural Analysis",
        "topic": "Slope Deflection Method",
        "subtopic": "Standard Equations",
        "stem": "In a prismatic beam AB with span L, flexural rigidity EI, and end rotations θA and θB with sinking Δ, the slope deflection equation for end moment MAB is:",
        "options": ["MAB = M_F_AB + (2EI/L) · [2θA + θB - 3Δ/L]", "MAB = M_F_AB + (4EI/L) · [θA + θB - Δ/L]", "MAB = M_F_AB + (2EI/L) · [θA + 2θB - 3Δ/L]", "MAB = M_F_AB + (3EI/L) · [θA - Δ/L]"],
        "correct": "A",
        "formula": "MAB = M_F_AB + (2EI/L) · [2θA + θB - 3Δ/L]",
        "explanation": "The classic slope-deflection equation derives directly from superposition of fixed-end moment, near-end rotation (4EI/L · θA), far-end rotation (2EI/L · θB), and relative chord rotation (-6EI/L² · Δ). Factoring out 2EI/L yields MAB = M_F_AB + (2EI/L)[2θA + θB - 3Δ/L].",
        "ref": "Elementary Structural Analysis by Norris & Wilbur",
        "diff": "MEDIUM",
        "year": 2024
    },
    {
        "qNum": 20,
        "subject": "Structural Analysis",
        "topic": "Influence Line Diagrams",
        "subtopic": "Müller-Breslau Principle",
        "stem": "Müller-Breslau’s Principle for constructing influence lines is applicable to:",
        "options": ["Statically determinate structures only", "Statically indeterminate structures only", "Both statically determinate and indeterminate structures", "Pin-jointed trusses only"],
        "correct": "C",
        "formula": "Based on Betti’s reciprocal theorem",
        "explanation": "Müller-Breslau principle is rooted in Maxwell-Betti reciprocal theorem and applies to all linear elastic structures, whether determinate or indeterminate. For determinate beams the ILD consists of straight line segments; for indeterminate beams it is curved.",
        "ref": "Structural Analysis by Devdas Menon",
        "diff": "EASY",
        "year": 2023
    },
    {
        "qNum": 21,
        "subject": "Structural Analysis",
        "topic": "Energy Theorems",
        "subtopic": "Castigliano’s Second Theorem",
        "stem": "Castigliano’s second theorem states that the partial derivative of total strain energy (U) with respect to an applied load (Pi) yields:",
        "options": ["The force in member i", "The deflection (Δi) at the point and in the direction of load Pi", "The slope at the point of load Pi", "The reaction at the nearest support"],
        "correct": "B",
        "formula": "∂U / ∂Pi = Δi",
        "explanation": "Castigliano’s theorem of least work / deflection states that in any linear elastic structure, ∂U/∂Pi = Δi, giving the displacement under load Pi along its line of action.",
        "ref": "Strength of Materials by Timoshenko",
        "diff": "EASY",
        "year": 2021
    },
    {
        "qNum": 22,
        "subject": "Structural Analysis",
        "topic": "Energy Methods",
        "subtopic": "Unit Load Method for Deflection",
        "stem": "In the unit load method for determining beam deflection, the expression for deflection Δ at any point is:",
        "options": ["Δ = ∫ (M · m / EI) dx", "Δ = ∫ (M² / 2EI) dx", "Δ = ∫ (m² / EI) dx", "Δ = ∫ (M · m / 2EI) dx"],
        "correct": "A",
        "formula": "Δ = ∫ (M · m / EI) dx",
        "explanation": "Based on virtual work principle: 1 · Δ = ∫ (m · ε) dx = ∫ m · (M / EI) dx = ∫ (M · m / EI) dx, where M is bending moment from actual loads and m is bending moment due to a fictitious unit load applied at the desired deflection point.",
        "ref": "Structural Analysis by Hibbeler",
        "diff": "MEDIUM",
        "year": 2024
    },
    {
        "qNum": 23,
        "subject": "Structural Analysis",
        "topic": "Arches",
        "subtopic": "Three-Hinged Parabolic Arch",
        "stem": "A three-hinged parabolic arch of span L and central rise h is subjected to a uniformly distributed load w over its entire span. The horizontal thrust (H) at the supports is:",
        "options": ["w · L² / (8 · h)", "w · L² / (16 · h)", "w · L / (8 · h)", "w · L² / (4 · h)"],
        "correct": "A",
        "formula": "H = w · L² / (8 · h)",
        "explanation": "Taking moments about the crown hinge C: Mc = (wL/2) · (L/2) - (w · (L/2)² / 2) - H · h = 0 => H · h = wL²/8 => H = wL² / (8h).",
        "ref": "Theory of Structures by Punmia",
        "diff": "EASY",
        "year": 2023
    },
    {
        "qNum": 24,
        "subject": "Structural Analysis",
        "topic": "Arches",
        "subtopic": "Bending Moment in Parabolic Arch",
        "stem": "For a three-hinged parabolic arch carrying a uniformly distributed load over its entire span, the bending moment at any section of the arch is:",
        "options": ["Zero everywhere", "Maximum at the quarter span", "Maximum at the crown", "Equal to wL²/8"],
        "correct": "A",
        "formula": "Mx = μx - H · y = 0",
        "explanation": "The parabolic profile y = 4hx(L-x)/L² exactly matches the bending moment shape of a simple beam under UDL. Hence the thrust moment (H · y) exactly cancels the beam moment (μx) at every cross section, resulting in zero bending moment throughout.",
        "ref": "Structural Analysis by Negi",
        "diff": "EASY",
        "year": 2022
    },
    {
        "qNum": 25,
        "subject": "Structural Analysis",
        "topic": "Cables and Suspension Bridges",
        "subtopic": "Maximum Tension in Cable",
        "stem": "A flexible cable of span L and central sag h carries a uniformly distributed load w per unit horizontal length. The maximum tension in the cable occurs at:",
        "options": ["The mid-span (lowest point)", "The supports", "Quarter-span points", "Uniform throughout the length"],
        "correct": "B",
        "formula": "Tmax = √(H² + V²) at support",
        "explanation": "Cable tension at any point is T = √(H² + Vy²). Since horizontal thrust H is constant throughout the cable and vertical shear Vy is maximum at the supports (V = wL/2), the resultant cable tension Tmax occurs at the supports.",
        "ref": "Structural Analysis by Bhavikatti",
        "diff": "EASY",
        "year": 2024
    },
    {
        "qNum": 26,
        "subject": "Structural Analysis",
        "topic": "Portal Frames",
        "subtopic": "Sway Analysis",
        "stem": "In portal frames, side sway will NOT occur if which of the following conditions is satisfied?",
        "options": ["The frame is symmetrical in geometry, member properties and loading", "The frame is subjected to unsymmetrical lateral load", "Columns have different cross sections and unequal lengths", "Supports are at different levels"],
        "correct": "A",
        "formula": "No sway condition: Symmetry in frame geometry + stiffness + loading",
        "explanation": "Sway is induced by asymmetry in geometry, unequal column stiffness, uneven support levels, or unsymmetrical lateral/gravity loading. If geometry, stiffness, support levels, and loading are all perfectly symmetrical, no sway occurs.",
        "ref": "Indeterminate Structural Analysis by Menon",
        "diff": "EASY",
        "year": 2021
    },
    {
        "qNum": 27,
        "subject": "Structural Analysis",
        "topic": "Plastic Analysis",
        "subtopic": "Shape Factor of Rectangular Section",
        "stem": "The shape factor (S = Zp / Ze) for a rectangular cross-section of width b and depth d is:",
        "options": ["1.0", "1.18", "1.50", "1.70"],
        "correct": "C",
        "formula": "Shape Factor S = Zp / Ze = (b d² / 4) / (b d² / 6) = 1.50",
        "explanation": "For a rectangular beam: Plastic section modulus Zp = (b · d/2) · (d/4) · 2 = b d² / 4. Elastic section modulus Ze = b d² / 6. Therefore, shape factor S = Zp / Ze = (b d² / 4) / (b d² / 6) = 1.50. For circular section S = 1.70, diamond S = 2.0, I-section S = 1.12 to 1.18.",
        "ref": "Plastic Analysis of Structures by Baker",
        "diff": "EASY",
        "year": 2024
    },

    # --- STRENGTH OF MATERIALS (SOM) (28 - 37) ---
    {
        "qNum": 28,
        "subject": "Strength of Materials",
        "topic": "Stress and Strain",
        "subtopic": "Elastic Constants Relationship",
        "stem": "The relationship connecting Young's modulus (E), Shear modulus (G), and Poisson's ratio (μ) for an isotropic elastic material is:",
        "options": ["E = 2G(1 + μ)", "E = 3G(1 - 2μ)", "E = 2G(1 - μ)", "G = 2E(1 + μ)"],
        "correct": "A",
        "formula": "E = 2G(1 + μ) and E = 3K(1 - 2μ)",
        "explanation": "From the theory of elasticity, the fundamental relationships among elastic constants are: E = 2G(1 + μ) = 3K(1 - 2μ) = 9KG / (3K + G).",
        "ref": "Mechanics of Materials by Gere & Timoshenko",
        "diff": "EASY",
        "year": 2024
    },
    {
        "qNum": 29,
        "subject": "Strength of Materials",
        "topic": "Elastic Constants",
        "subtopic": "Poisson's Ratio Upper Bound",
        "stem": "For a perfectly incompressible isotropic material, the theoretical value of Poisson's ratio (μ) is:",
        "options": ["0", "0.25", "0.33", "0.50"],
        "correct": "D",
        "formula": "Volumetric strain εv = (σx + σy + σz)/E · (1 - 2μ) = 0 => μ = 0.50",
        "explanation": "Volumetric strain for isotropic material is given by εv = (σx+σy+σz)/E · (1 - 2μ). For an incompressible material, volume change is zero (εv = 0), which mathematically requires (1 - 2μ) = 0 => μ = 0.50. For cork μ ≈ 0; for rubber μ ≈ 0.49 - 0.50.",
        "ref": "Strength of Materials by Rajput",
        "diff": "EASY",
        "year": 2023
    },
    {
        "qNum": 30,
        "subject": "Strength of Materials",
        "topic": "Principal Stresses",
        "subtopic": "Mohr's Circle Radius",
        "stem": "In a 2D stress system with normal stresses σx and σy and shear stress τxy, the radius of Mohr's circle of stress is equal to:",
        "options": ["(σx + σy) / 2", "√[((σx - σy)/2)² + τxy²]", "√[((σx + σy)/2)² + τxy²]", "(σx - σy) / 2"],
        "correct": "B",
        "formula": "R = τmax = √[((σx - σy)/2)² + τxy²]",
        "explanation": "The center of Mohr's circle is located at ((σx + σy)/2, 0) and its radius R represents the maximum in-plane shear stress τmax = √[((σx - σy)/2)² + τxy²].",
        "ref": "Strength of Materials by Sadhu Singh",
        "diff": "EASY",
        "year": 2022
    },
    {
        "qNum": 31,
        "subject": "Strength of Materials",
        "topic": "Principal Planes",
        "subtopic": "Shear Stress on Principal Planes",
        "stem": "On principal planes in a stressed body, the value of shear stress is always:",
        "options": ["Maximum", "Minimum but non-zero", "Zero", "Equal to normal stress"],
        "correct": "C",
        "formula": "τ = 0 on principal planes",
        "explanation": "By definition, principal planes are planes of zero shear stress. The normal stresses acting on these planes are known as the principal stresses (major and minor).",
        "ref": "Mechanics of Solids by Popov",
        "diff": "EASY",
        "year": 2024
    },
    {
        "qNum": 32,
        "subject": "Strength of Materials",
        "topic": "Shear Force & Bending Moment",
        "subtopic": "Point of Contraflexure",
        "stem": "A point of contraflexure (or inflection) in a loaded beam is a point where:",
        "options": ["Shear force is zero", "Bending moment is zero or changes sign", "Bending moment is maximum", "Shear force changes sign"],
        "correct": "B",
        "formula": "M(x) = 0 and d²M/dx² ≠ 0 (curvature changes sign)",
        "explanation": "A point of contraflexure is defined as a point along the beam span where the bending moment curve crosses zero and changes sign (from sagging to hogging or vice-versa). The beam curvature changes direction at this point.",
        "ref": "Strength of Materials by B.C. Punmia",
        "diff": "EASY",
        "year": 2023
    },
    {
        "qNum": 33,
        "subject": "Strength of Materials",
        "topic": "Bending Stresses",
        "subtopic": "Flexure Formula",
        "stem": "In the simple bending theory (Euler-Bernoulli beam theory), the bending stress (σ) at a distance y from the neutral axis is given by:",
        "options": ["σ = M · y / I", "σ = M · I / y", "σ = I · y / M", "σ = M / (I · y)"],
        "correct": "A",
        "formula": "M / I = σ / y = E / R => σ = M · y / I",
        "explanation": "The classic flexure equation is M/I = σ/y = E/R. Hence bending stress σ varies linearly across the cross-section, being zero at the neutral axis and maximum at the extreme fibers (y = ymax).",
        "ref": "Strength of Materials by R.K. Bansal",
        "diff": "EASY",
        "year": 2021
    },
    {
        "qNum": 34,
        "subject": "Strength of Materials",
        "topic": "Shear Stresses in Beams",
        "subtopic": "Maximum Shear Stress in Rectangular Section",
        "stem": "For a beam of rectangular cross-section of width b and depth d, the maximum shear stress (τmax) is related to the average shear stress (τavg) by:",
        "options": ["τmax = 1.20 τavg", "τmax = 1.33 τavg", "τmax = 1.50 τavg", "τmax = 2.00 τavg"],
        "correct": "C",
        "formula": "τmax = 1.50 · τavg (Rectangular); τmax = 1.33 · τavg (Circular)",
        "explanation": "The parabolic shear stress distribution for a rectangle is τ = (V / 2I) · (d²/4 - y²). At the neutral axis (y = 0), τmax = 1.5 · (V / bd) = 1.50 · τavg.",
        "ref": "Mechanics of Materials by Beer & Johnston",
        "diff": "EASY",
        "year": 2024
    },
    {
        "qNum": 35,
        "subject": "Strength of Materials",
        "topic": "Torsion of Circular Shafts",
        "subtopic": "Torsion Equation",
        "stem": "A solid circular shaft of diameter D is subjected to a torque T. The maximum shear stress induced at the outer surface is:",
        "options": ["16 T / (π D³)", "32 T / (π D³)", "64 T / (π D³)", "8 T / (π D³)"],
        "correct": "A",
        "formula": "τmax = T · r / J = T · (D/2) / (π D⁴ / 32) = 16 T / (π D³)",
        "explanation": "From the torsion formula T/J = τ/r, for a solid circular shaft J = π D⁴ / 32 and r = D/2. Thus τmax = 16 T / (π D³). Polar section modulus Zp = π D³ / 16.",
        "ref": "Strength of Materials by S. Ramamrutham",
        "diff": "EASY",
        "year": 2023
    },
    {
        "qNum": 36,
        "subject": "Strength of Materials",
        "topic": "Deflection of Beams",
        "subtopic": "Cantilever with Point Load",
        "stem": "What is the maximum deflection at the free end of a cantilever beam of span L and flexural rigidity EI carrying a concentrated point load P at its free end?",
        "options": ["P L³ / (3 EI)", "P L³ / (8 EI)", "P L³ / (48 EI)", "5 P L⁴ / (384 EI)"],
        "correct": "A",
        "formula": "δmax = P L³ / (3 EI); θmax = P L² / (2 EI)",
        "explanation": "By moment area theorem or double integration: Deflection δ = P L³ / (3 EI). For UDL over entire span, δ = w L⁴ / (8 EI). For simply supported beam with central load, δ = P L³ / (48 EI).",
        "ref": "Theory of Structures by Vazirani & Ratwani",
        "diff": "EASY",
        "year": 2022
    },
    {
        "qNum": 37,
        "subject": "Strength of Materials",
        "topic": "Columns & Struts",
        "subtopic": "Euler Buckling Load & Effective Length",
        "stem": "A long column of length L and flexural rigidity EI has both ends pinned (hinged). According to Euler's formula, the critical crippling load (Pcr) is:",
        "options": ["π² EI / L²", "4 π² EI / L²", "π² EI / (4 L²)", "2 π² EI / L²"],
        "correct": "A",
        "formula": "Pcr = π² EI / Leff²; Leff = L (both ends hinged)",
        "explanation": "Euler crippling load Pcr = π² EI / Leff². For both ends hinged: Leff = L => Pcr = π² EI / L². For both ends fixed: Leff = L/2 => Pcr = 4 π² EI / L². For one fixed and one free: Leff = 2L => Pcr = π² EI / (4 L²). For one fixed and one hinged: Leff = L/√2 => Pcr = 2 π² EI / L².",
        "ref": "Mechanics of Materials by Gere",
        "diff": "EASY",
        "year": 2024
    },

    # --- GEOTECHNICAL & SOIL MECHANICS (38 - 52) ---
    {
        "qNum": 38,
        "subject": "Geotechnical Engineering",
        "topic": "Soil Properties & Phase Relationships",
        "subtopic": "Fundamental Relationship",
        "stem": "In soil mechanics, which of the following equations correctly connects degree of saturation (S), void ratio (e), water content (w), and specific gravity (G)?",
        "options": ["S · e = w · G", "S · w = e · G", "S · G = w · e", "w · e · S = G"],
        "correct": "A",
        "formula": "S · e = w · G",
        "explanation": "By definition, S = Vw / Vv and e = Vv / Vs => S · e = Vw / Vs = (Mw / ρw) / (Ms / (G · ρw)) = (Mw / Ms) · G = w · G. Hence S · e = w · G.",
        "ref": "Soil Mechanics & Foundation Engineering by K.R. Arora",
        "diff": "EASY",
        "year": 2024
    },
    {
        "qNum": 39,
        "subject": "Geotechnical Engineering",
        "topic": "Soil Classification",
        "subtopic": "Plasticity Chart & A-Line Equation",
        "stem": "In the Indian Standard Soil Classification System (IS 1498), the equation of the 'A-line' on the plasticity chart separating clays from silts and organic soils is:",
        "options": ["IP = 0.73 · (wL - 20)", "IP = 0.90 · (wL - 8)", "IP = 0.73 · (wL - 10)", "IP = 0.50 · (wL - 20)"],
        "correct": "A",
        "formula": "IP = 0.73 · (wL - 20)",
        "explanation": "Arthur Casagrande's A-line equation is IP = 0.73 · (wL - 20). Inorganic clays lie above the A-line; inorganic silts and organic clays lie below the A-line. The U-line (upper limit) is IP = 0.90 · (wL - 8).",
        "ref": "IS 1498:1970 Soil Classification Code",
        "diff": "EASY",
        "year": 2023
    },
    {
        "qNum": 40,
        "subject": "Geotechnical Engineering",
        "topic": "Effective Stress Principle",
        "subtopic": "Terzaghi's Principle",
        "stem": "According to Terzaghi's effective stress principle, total stress (σ), effective stress (σ'), and pore water pressure (u) are related by:",
        "options": ["σ' = σ - u", "σ' = σ + u", "σ' = u - σ", "σ' = σ / u"],
        "correct": "A",
        "formula": "σ' = σ - u",
        "explanation": "The effective stress σ' is the intergranular stress transmitted across grain contacts that governs shear strength and volume compressibility: σ' = σ - u.",
        "ref": "Theoretical Soil Mechanics by Terzaghi",
        "diff": "EASY",
        "year": 2022
    },
    {
        "qNum": 41,
        "subject": "Geotechnical Engineering",
        "topic": "Permeability of Soils",
        "subtopic": "Constant vs Falling Head Permeameter",
        "stem": "The falling head permeability test is primarily recommended for which type of soil?",
        "options": ["Clean gravels", "Coarse sands", "Fine-grained soils like silts and clays", "Boulders and cobbles"],
        "correct": "C",
        "formula": "k = (2.303 a L / (A t)) · log10(h1 / h2)",
        "explanation": "Constant head permeameter is used for coarse-grained soils with high permeability (sands, gravels). Falling head permeameter is suitable for fine-grained soils (silts and clays) where discharge is very small.",
        "ref": "Basic and Applied Soil Mechanics by Gopal Ranjan",
        "diff": "EASY",
        "year": 2024
    },
    {
        "qNum": 42,
        "subject": "Geotechnical Engineering",
        "topic": "Seepage & Flow Nets",
        "subtopic": "Seepage Discharge Equation",
        "stem": "In a flow net constructed with Nf flow channels and Nd equipotential drops under total head loss H, the seepage discharge per unit length through soil of permeability k is:",
        "options": ["q = k · H · (Nf / Nd)", "q = k · H · (Nd / Nf)", "q = k · H · (Nf · Nd)", "q = k · H / (Nf + Nd)"],
        "correct": "A",
        "formula": "q = k · H · (Nf / Nd)",
        "explanation": "Flow net discharge is given by q = k · H · (Nf / Nd) for square flow elements where aspect ratio b/a = 1. Shape factor is defined as (Nf / Nd).",
        "ref": "Soil Mechanics by B.C. Punmia",
        "diff": "EASY",
        "year": 2023
    },
    {
        "qNum": 43,
        "subject": "Geotechnical Engineering",
        "topic": "Quick Sand Condition",
        "subtopic": "Critical Hydraulic Gradient",
        "stem": "The critical hydraulic gradient (icr) at which quicksand condition or boiling occurs in a saturated cohesionless soil is given by:",
        "options": ["icr = (G - 1) / (1 + e)", "icr = (G + 1) / (1 + e)", "icr = (G - 1) / (1 - e)", "icr = (1 + e) / (G - 1)"],
        "correct": "A",
        "formula": "icr = γ' / γw = (G - 1) / (1 + e)",
        "explanation": "Quicksand occurs when upward seepage force balances submerged weight of soil particles (effective stress σ' = 0). Thus i · γw = γ' => icr = γ' / γw = (G - 1) / (1 + e). For typical soils (G ≈ 2.65, e ≈ 0.65), icr ≈ 1.0.",
        "ref": "Soil Mechanics in Engineering Practice by Terzaghi & Peck",
        "diff": "EASY",
        "year": 2021
    },
    {
        "qNum": 44,
        "subject": "Geotechnical Engineering",
        "topic": "Consolidation of Soils",
        "subtopic": "Time Factor and Drainage Path",
        "stem": "In Terzaghi's 1D consolidation theory, the non-dimensional time factor (Tv) is expressed as:",
        "options": ["Tv = Cv · t / d²", "Tv = Cv · d² / t", "Tv = k · t / Cv", "Tv = mv · t / d²"],
        "correct": "A",
        "formula": "Tv = Cv · t / d²",
        "explanation": "Time factor Tv = Cv · t / d², where Cv is coefficient of consolidation, t is time, and d is length of drainage path (d = H/2 for two-way double drainage, d = H for single one-way drainage).",
        "ref": "Geotechnical Engineering by C. Venkatramaiah",
        "diff": "EASY",
        "year": 2024
    },
    {
        "qNum": 45,
        "subject": "Geotechnical Engineering",
        "topic": "Consolidation of Soils",
        "subtopic": "Compression Index Empirical Formula",
        "stem": "For undisturbed clays of medium to low sensitivity, Skempton's empirical formula for compression index (Cc) based on liquid limit (wL in %) is:",
        "options": ["Cc = 0.009 · (wL - 10)", "Cc = 0.007 · (wL - 10)", "Cc = 0.009 · (wL - 20)", "Cc = 0.005 · (wL - 15)"],
        "correct": "A",
        "formula": "Cc = 0.009 · (wL - 10) for undisturbed clays",
        "explanation": "Skempton's widely verified empirical relationship is: Cc = 0.009 · (wL - 10) for undisturbed clays, and Cc = 0.007 · (wL - 10) for remolded clays.",
        "ref": "Soil Mechanics by Lambe & Whitman",
        "diff": "MEDIUM",
        "year": 2023
    },
    {
        "qNum": 46,
        "subject": "Geotechnical Engineering",
        "topic": "Shear Strength of Soil",
        "subtopic": "Mohr-Coulomb Failure Criteria",
        "stem": "The shear strength (τf) of a soil on any plane according to Mohr-Coulomb failure criterion is represented by:",
        "options": ["τf = c + σ · tan φ", "τf = c - σ · tan φ", "τf = σ + c · tan φ", "τf = c · σ · tan φ"],
        "correct": "A",
        "formula": "τf = c + σ · tan φ (Total) or τf = c' + σ' · tan φ' (Effective)",
        "explanation": "Coulomb's shear strength equation states that shear strength comprises apparent cohesion c and frictional resistance proportional to effective normal stress σ: τf = c + σ tan φ.",
        "ref": "Principles of Geotechnical Engineering by B.M. Das",
        "diff": "EASY",
        "year": 2022
    },
    {
        "qNum": 47,
        "subject": "Geotechnical Engineering",
        "topic": "Shear Strength Testing",
        "subtopic": "Triaxial Drainage Conditions",
        "stem": "In a Consolidated Undrained (CU) triaxial compression test, drainage is permitted during:",
        "options": ["The application of cell pressure only", "The application of deviator stress only", "Both cell pressure and deviator stress stages", "Neither cell pressure nor deviator stress stage"],
        "correct": "A",
        "formula": "CU test: Drainage open during cell pressure consolidation, closed during shearing",
        "explanation": "In Consolidated Undrained (CU) test: Consolidation stage has drainage valve open (dissipating excess pore pressure under confining pressure σ3); during the subsequent shearing stage (application of deviator stress Δσ), the drainage valve is closed.",
        "ref": "Soil Mechanics by Craig",
        "diff": "MEDIUM",
        "year": 2024
    },
    {
        "qNum": 48,
        "subject": "Geotechnical Engineering",
        "topic": "Lateral Earth Pressure",
        "subtopic": "Rankine's Active Pressure Coefficient",
        "stem": "For a cohesionless backfill with horizontal ground surface and angle of internal friction φ, Rankine's coefficient of active earth pressure (Ka) is:",
        "options": ["Ka = (1 - sin φ) / (1 + sin φ)", "Ka = (1 + sin φ) / (1 - sin φ)", "Ka = cos² φ / (1 + sin φ)", "Ka = (1 - cos φ) / (1 + cos φ)"],
        "correct": "A",
        "formula": "Ka = (1 - sin φ) / (1 + sin φ) = tan²(45° - φ/2)",
        "explanation": "Rankine's active coefficient is Ka = (1 - sin φ) / (1 + sin φ) = tan²(45° - φ/2). Conversely, passive pressure coefficient Kp = 1 / Ka = (1 + sin φ) / (1 - sin φ) = tan²(45° + φ/2).",
        "ref": "Foundation Engineering by Teng",
        "diff": "EASY",
        "year": 2023
    },
    {
        "qNum": 49,
        "subject": "Geotechnical Engineering",
        "topic": "Bearing Capacity of Foundations",
        "subtopic": "Terzaghi's Equation for Strip Footing",
        "stem": "Terzaghi's ultimate bearing capacity (qu) equation for a continuous strip footing of width B at depth Df in soil with parameters c, γ, and bearing capacity factors Nc, Nq, Nγ is:",
        "options": ["qu = c Nc + q Nq + 0.5 γ B Nγ", "qu = 1.3 c Nc + q Nq + 0.4 γ B Nγ", "qu = 1.3 c Nc + q Nq + 0.3 γ B Nγ", "qu = c Nc + q Nq + γ B Nγ"],
        "correct": "A",
        "formula": "qu = c Nc + γ Df Nq + 0.5 γ B Nγ",
        "explanation": "For a strip footing: qu = c Nc + q Nq + 0.5 γ B Nγ. For a square footing: qu = 1.3 c Nc + q Nq + 0.4 γ B Nγ. For a circular footing: qu = 1.3 c Nc + q Nq + 0.3 γ B Nγ.",
        "ref": "Theoretical Soil Mechanics by Terzaghi",
        "diff": "EASY",
        "year": 2024
    },
    {
        "qNum": 50,
        "subject": "Geotechnical Engineering",
        "topic": "Bearing Capacity Definitions",
        "subtopic": "Net Ultimate Bearing Capacity",
        "stem": "The net ultimate bearing capacity (qnu) of a foundation is defined in terms of gross ultimate bearing capacity (qu) and effective surcharge (q = γ Df) as:",
        "options": ["qnu = qu - γ · Df", "qnu = qu + γ · Df", "qnu = qu / (γ · Df)", "qnu = (qu - γ · Df) / FOS"],
        "correct": "A",
        "formula": "qnu = qu - q = qu - γ · Df",
        "explanation": "Net ultimate bearing capacity is the net intensity of pressure at the base of the footing in excess of the existing overburden pressure that the soil can support: qnu = qu - γ Df. Net safe bearing capacity qns = qnu / FOS.",
        "ref": "Soil Mechanics by B.C. Punmia",
        "diff": "EASY",
        "year": 2021
    },
    {
        "qNum": 51,
        "subject": "Geotechnical Engineering",
        "topic": "Standard Penetration Test (SPT)",
        "subtopic": "Dilatancy Correction",
        "stem": "The dilatancy correction for observed SPT N-value in fine sands and silts below water table is applied only when the corrected value for overburden (N1) exceeds 15, using the formula:",
        "options": ["N'' = 15 + 0.5 · (N' - 15)", "N'' = 15 + 0.75 · (N' - 15)", "N'' = 15 + 0.25 · (N' - 15)", "N'' = 0.5 · (N' + 15)"],
        "correct": "A",
        "formula": "N'' = 15 + 0.5 · (N' - 15) per IS 2131",
        "explanation": "As per IS 2131, negative pore water pressures during dynamic shearing increase resistance in dense saturated silts and fine sands. When N' > 15, the dilatancy correction is N'' = 15 + 0.5(N' - 15).",
        "ref": "IS 2131:1981 Standard Penetration Test Code",
        "diff": "MEDIUM",
        "year": 2024
    },
    {
        "qNum": 52,
        "subject": "Geotechnical Engineering",
        "topic": "Pile Foundations",
        "subtopic": "Negative Skin Friction",
        "stem": "Negative skin friction on a driven pile occurs when:",
        "options": ["The surrounding soil settles more than the pile itself", "The pile moves downward relative to the soil under structural load", "The pile is driven into very hard bedrock", "Groundwater level rises rapidly above the surface"],
        "correct": "A",
        "formula": "Downward drag force Qnf = P · L · α · c",
        "explanation": "Negative skin friction is a downward drag acting on pile shaft when consolidating compressible soil (soft clay, recent fill) settles faster than the pile, adding downward load to the pile instead of providing upward support.",
        "ref": "Foundation Engineering by Bowles",
        "diff": "EASY",
        "year": 2023
    }
]

print(f"Loaded {len(civil_questions)} questions so far.")
